CC=gcc
CFLAGS=-I. -pthread

all: sislog client

sislog: # TO FILL OUT DEPENDENCIES
	# TODO
	|
	|

client: # TO FILL OUT DEPENDENCIES
	# TODO
	|
	|


clean:
	-rm *.o

cleanall: clean
	-rm sislog client *.dat
